
-- שאלות עבור קטגוריה: accessibility
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('accessibility_questionnaire_id', '1. האם קיימת חניית נכים תקנית בסמוך לכניסה למתנ"ס?', 1, 
                 'נגישות פיזית', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '2. האם קיימת גישה נגישה (רמפה תקנית) מהחניה ועד לכניסה למבנה?', 2, 
                 'נגישות פיזית', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '3. האם קיימים שירותי נכים תקניים?', 3, 
                 'נגישות פיזית', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '4. האם קיים רכז נגישות במתנ"ס?', 4, 
                 'נגישות שירות', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '5. האם צוות המתנ"ס עבר הדרכת נגישות השירות?', 5, 
                 'נגישות שירות', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '6. האם אתר האינטרנט של המתנ"ס נגיש בהתאם לתקנות?', 6, 
                 'נגישות דיגיטלית', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '7. האם קיימת אפשרות לקבלת מידע בפורמטים נגישים (הקראה, כתב מוגדל, ברייל)?', 7, 
                 'נגישות דיגיטלית', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '8. האם קיימת מערכת עזר לשמיעה (מערכת הגברה/לולאת השראה)?', 8, 
                 'אמצעי עזר והתאמות', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '9. האם קיים שילוט הכוונה נגיש (כולל ברייל)?', 9, 
                 'אמצעי עזר והתאמות', 
                 'radio_with_text', true),
                ('accessibility_questionnaire_id', '10. האם קיימים אמצעי עזר להנגשת פעילויות (ציוד מותאם, עזרים טכנולוגיים)?', 10, 
                 'אמצעי עזר והתאמות', 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: accounting
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('accounting_questionnaire_id', '1. האם הועברו יתרות סגירה משנה קודמת?', 1, 
                 'סגירת ופתיחת שנה', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '2. האם הושלמו כל תהליכי סגירת שנה ופתיחת שנה?', 2, 
                 'סגירת ופתיחת שנה', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '3. האם מתבצעות התאמות בנקים באופן שוטף?', 3, 
                 'התאמות ובקרה', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '4. האם קיימת התאמה בין מערכת הגבייה למערכת הנהלת החשבונות?', 4, 
                 'התאמות ובקרה', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '5. האם מתבצע עיבוד אוטומטי של דפי הבנק?', 5, 
                 'ממשקים ואוטומציה', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '6. האם מתבצעות התאמות בין המערכות לאחר העברות?', 6, 
                 'ממשקים ואוטומציה', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '7. האם מתבצעת התאמת חייבים וזכאים שנתית?', 7, 
                 'בקרה ומעקב', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '8. האם מתבצעת בקרה על חובות מסופקים?', 8, 
                 'בקרה ומעקב', 
                 'radio_with_text', true),
                ('accounting_questionnaire_id', '9. האם מתבצעת בקרה על הוצאות קבועות?', 9, 
                 'בקרה ומעקב', 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: budget
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('budget_questionnaire_id', '1. האם נקבעה מדיניות המתנ"ס לשנה הקרובה בהנהלת המתנ"ס?', 1, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true),
                ('budget_questionnaire_id', '2. האם השתתפות הרשות ומשרדי הממשלה בתקציב המתנ"ס קטנה מ-50% (רלוונטי לעמותה מעין עירונית)?', 2, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true),
                ('budget_questionnaire_id', '3. האם התקציב נערך באמצעות תוכנה ייעודית (כגון: תכנת ת.מ.ר של החברה)?', 3, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true),
                ('budget_questionnaire_id', '4. האם התקציב נערך על בסיס חודשי ריאלי לכל פעילות?', 4, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true),
                ('budget_questionnaire_id', '5. האם התקציב כולל השוואה לתקציב וצפי ביצוע שנה קודמת?', 5, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true),
                ('budget_questionnaire_id', '6. האם הועברה הצעת התקציב בצירוף הסברים לחברי ההנהלה, למא"ז ולבקר הכספי לפחות שבוע לפני הדיון בהנהלה?', 6, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true),
                ('budget_questionnaire_id', '7. האם התקציב אושר על ידי ההנהלה (ובעמותות מעין עירוניות גם במועצת העיר)?', 7, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true),
                ('budget_questionnaire_id', '8. האם מתבצע עדכון תקציב במהלך השנה?', 8, 
                 'הכנת תקציב למתנ"ס', 
                 'radio', true),
                ('budget_questionnaire_id', '9. האם עדכון התקציב עובר את כל תהליכי האישור הנדרשים?', 9, 
                 'הכנת תקציב למתנ"ס', 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: community
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('community_questionnaire_id', 'האם נעשתה הכשרה להנהלת המרכז הקהילתי בנושא אסטרטגית החברה?', 1, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם הנהלת המרכז הקהילתי שותפה בהגדרת מדיניות חברתית-קהילתית?', 2, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למנהל המרכז הקהילתי תכנית להגברת קהילתיות בצוות (כולל שגרות ניהול)?', 3, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למרכז הקהילתי רכז/ראש תחום קהילה במשרה מלאה?', 4, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם צוות המרכז הקהילתי בקיא בשפה הארגונית לתחום קהילה?', 5, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם המרכז הקהילתי ערך מיפוי ואבחון קהילתי?', 6, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם בתכנית העבודה השנתית הוגדרו לפחות 5 יעדים חברתיים-קהילתיים משותפים?', 7, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למרכז הקהילתי תכנית להגברת קהילתיות במסגרות הפעילות השוטפת?', 8, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם המרכז הקהילתי עבר בשנתיים האחרונות תהליך עומק לתחום בינוי קהילה/תשתיות?', 9, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למרכז הקהילתי מיפוי ואבחון הכולל אפיון הקשר עם כל הקבוצות ביישוב/בשכונה?', 10, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם יש איש צוות האחראי לתחום ההתנדבות והמעורבות במרכז הקהילתי?', 11, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם המרכז הקהילתי מפעיל מערך מתנדבים ופעילים בשגרה של לפחות 100 תושבים?', 12, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למרכז הקהילתי קיים מערך פעילים ומתנדבים לשעת חירום?', 13, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם המרכז הקהילתי מוביל או שותף לשולחן עגול יישובי לתחום התנדבות?', 14, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם הנושא נדון בהנהלה הציבורית בשנה האחרונה?', 15, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם קיימת וועדת הנהלה בנושא?', 16, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למרכז הקהילתי תכנית שנתית לקידום התנדבות ומעורבות חברתית?', 17, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם המרכז הקהילתי קידם לפחות שלוש יוזמות קהילתיות בשנת הפעילות האחרונה?', 18, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם ניהול המתנדבים מבוצע באמצעות תוכנה לניהול מתנדבים?', 19, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'למרכז הקהילתי יש מתנדבים ופעילים לתחום זהויות?', 20, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למרכז הקהילתי לוח שנה ארגוני הכולל לפחות 5 אירועים בוני קהילה?', 21, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם המרכז הקהילתי מפעיל תכניות/יוזמות לקידום הקשר בין קבוצות אוכלוסייה שונות?', 22, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם המרכז הקהילתי מעורב או מוביל חג יישוב בקהילתו?', 23, 
                 NULL, 
                 'radio_with_text', true),
                ('community_questionnaire_id', 'האם למרכז הקהילתי קשר מקצועי עם המחלקה לזהויות/ארגוני זהות אחרים?', 24, 
                 NULL, 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: financial
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('financial_questionnaire_id', 'האם יש מדיניות ברורה לתשלום לספקים?', 1, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם המרכז משתמש בהעברות בנקאיות כאמצעי תשלום עיקרי לספקים?', 2, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם קיימת מערכת ממוחשבת לניהול תשלומים לספקים?', 3, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם יש בקרה על תשלומים לספקים?', 4, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם יש נוהל קבוע לתשלומים שוטפים?', 5, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם למרכז יש כיסוי ביטוחי מתאים לכלל הפעילויות?', 6, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם יש תהליך מסודר לטיפול בתביעות ביטוח?', 7, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם המרכז נעזר ביועץ ביטוח מקצועי?', 8, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם המשתתפים נדרשים להצהיר על ביטוח אישי לפעילויות?', 9, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם קיים ביטוח למבנה המרכז עצמו?', 10, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם קיים תהליך אישור מסודר לרכישות במרכז?', 11, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם יש הגבלה תקציבית על רכישות מסוימות?', 12, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם מתנהלים מכרזים עבור רכישות גדולות?', 13, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם מתבצעת בקרת איכות על המוצרים והשירותים שנרכשו?', 14, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם קיים מעקב אחר מלאי הציוד במרכז?', 15, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם הרישום לפעילויות מתבצע באופן מקוון?', 16, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם הגבייה עבור פעילויות מתבצעת מראש?', 17, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם קיימות הנחות או הסדרי תשלומים לאוכלוסיות מסוימות?', 18, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם יש מדיניות לטיפול בחובות או אי-תשלום?', 19, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם קיימת אפשרות לפריסת תשלומים?', 20, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם יש אחראי מוגדר לניהול הקופה הקטנה?', 21, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם קיימת מגבלת סכום להוצאות מהקופה הקטנה?', 22, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם מתבצע תיעוד מסודר של ההוצאות בקופה הקטנה?', 23, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם מתקיימות ביקורות תקופתיות לניהול הקופה הקטנה?', 24, 
                 NULL, 
                 'radio_with_text', true),
                ('financial_questionnaire_id', 'האם יש תהליך מסודר להשלמת מזומנים בקופה הקטנה?', 25, 
                 NULL, 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: hr
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('hr_questionnaire_id', 'האם רישום נוכחות חל על כל העובדים?', 1, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם הנוכחות משתקפת בתלוש השכר כמתחייב בחוק להגברת האכיפה?', 2, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם קיימת מדיניות לביצוע שעות נוספות?', 3, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם האיסור מתועד בתיק האישי של העובד?', 4, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם מבוצעת התאמה בין הדיווח למכסת שעות המאושרות לעובד?', 5, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם מערכת הנוכחות מבצעת השלמת שעות נוכחות ללא חובת דיווח יציאה?', 6, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'יש מדיניות מחייבת לגובה ימי החופשה השנתיים הניתנים לעובדים?', 7, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'מספר ימי החופשה השנתיים נקבע בהתאם לחוק?', 8, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'נקבעה מדיניות לגבי צבירה שלילית של ימי חופשה?', 9, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם ניתן אישור בכתב בדבר בקשת העובד ליציאה לחופשה?', 10, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'נקבעה מדיניות בהנהלת המתנ"ס בדבר מתן ימי בחירה והצהרה לעובדי המתנ"ס?', 11, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'מספר ימי המחלה השנתיים נקבע בהתאם לחוק?', 12, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'המדיניות בדבר ימי המחלה הניתנים לעובד אושרה בישיבת הנהלת העמותה?', 13, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם הועדה קובעת את תנאי ההעסקה וקידומם של העובדים?', 14, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם הוועדה מאשרת שינויים בשכר העובדים?', 15, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם האצילה ההנהלה למנהל הנוכחי סמכויות לקבלת עובדים?', 16, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם האצלה זו נרשמה בפרוטוקול ישיבת ההנהלה?', 17, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם אתם פועלים עפ"י חוק הודעה לעובד ביחס למועמדים לכל תפקיד?', 18, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'ההסכם נחתם על ידי מורשי החתימה במתנ"ס והעובד?', 19, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם החוזים ממוחשבים ומוקלדים?', 20, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'אישור העסקה ממשטרת ישראל בדבר היעדר עבריינות מין?', 21, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם קיימת הלימה בין חוזה ההעסקה לתלוש השכר?', 22, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם קיימים במתנ"ס עובדי צינור?', 23, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם נקבעו ישיבות מראש לשנת העבודה?', 24, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'קיום קוורום בישיבות (עמותות - 5 מינימום, סוכנותי - 3 מינימום)?', 25, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם נערך פרוטוקול בגין כל ישיבה?', 26, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם נערך פרוטוקול מסודר לכל ישיבת ועדת כוח-אדם?', 27, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם הפרוטוקול נשמר בקומקס?', 28, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם היו"ר ההנהלה חותם על כל הפרוטוקולים?', 29, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם ההנהלה אישרה את תקציב המתנ"ס?', 30, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם הדוחות הכספיים אושרו במועד (סוכנותי עד סוף יוני, עמותות - עד סוף אפריל)?', 31, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'קיומו של פנקס חברי עמותה/הנהלה מעודכן?', 32, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם נערך מעקב אחר יישום ההחלטות?', 33, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם חברי ההנהלה קיבלו השתלמות מקצועית בשנה האחרונה?', 34, 
                 NULL, 
                 'radio_with_text', true),
                ('hr_questionnaire_id', 'האם להנהלה וועדות רשות?', 35, 
                 NULL, 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: inventory
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('inventory_questionnaire_id', '1. האם רישום המלאי ממוחשב?', 1, 
                 'רישום וניהול מלאי', 
                 'radio_with_text', true),
                ('inventory_questionnaire_id', '2. האם מנוהל ספר מלאי?', 2, 
                 'רישום וניהול מלאי', 
                 'radio_with_text', true),
                ('inventory_questionnaire_id', '3. האם נפתח כרטיס בהנהלת החשבונות לרישום ציוד ומלאי?', 3, 
                 'טיפול בציוד חסר', 
                 'radio_with_text', true),
                ('inventory_questionnaire_id', '4. האם הציוד שנמצא חסר נגרע מהרישום בכרטסת?', 4, 
                 'טיפול בציוד חסר', 
                 'radio_with_text', true),
                ('inventory_questionnaire_id', '5. האם גריעת הציוד נעשית באישור בכתב מהמנהל בהסתמך על פרוטוקול ההנהלה?', 5, 
                 'טיפול בציוד חסר', 
                 'radio_with_text', true),
                ('inventory_questionnaire_id', '6. האם המתנ"ס מגיש מיידית תלונה למשטרה במקרה של פריצה?', 6, 
                 'טיפול בציוד חסר', 
                 'radio_with_text', true),
                ('inventory_questionnaire_id', '7. האם נערך בשלוחה דו"ח מלאי?', 7, 
                 'טיפול בציוד חסר', 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: legal
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('legal_questionnaire_id', '1. האם קיימים חוזי העסקה חתומים לכל העובדים?', 1, 
                 NULL, 
                 'radio_with_text', true),
                ('legal_questionnaire_id', '2. האם קיימים הסכמי שכירות בתוקף לכל המבנים?', 2, 
                 NULL, 
                 'radio_with_text', true),
                ('legal_questionnaire_id', '3. האם קיימות פוליסות ביטוח בתוקף?', 3, 
                 NULL, 
                 'radio_with_text', true),
                ('legal_questionnaire_id', '4. האם קיימים טפסי הצהרת בריאות חתומים למשתתפי החוגים?', 4, 
                 NULL, 
                 'radio_with_text', true),
                ('legal_questionnaire_id', '5. האם קיים תקנון מאושר למרכז הקהילתי?', 5, 
                 NULL, 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: salary
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('salary_questionnaire_id', '1. האם חשבת השכר בעלת ידע והכשרה מקצועית נאותה (לכל הפחות עברה קורס חשבי שכר)?', 1, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '2. האם חשבת השכר בודקת את כל טיוטות תלושי השכר, בהתאם לנוהל השכר?', 2, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '3. האם מנהל המתנ"ס בודק מדגמית את תלושי העובדים למול גליונות הנוכחות (במקרה של פחות מ-50 עובדים - בדיקה של כלל התלושים)?', 3, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '4. האם מנהל המתנ"ס עורך בקרות שכר חודשיות על פי הדוחות הבאים:', 4, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '5. האם תשלום השכר נעשה עד ליום הקובע (ולא מאוחר מכך)?', 5, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '6. האם עד ה-15 לכל חודש מכינים דוח לביטוח לאומי עבור החודש הקודם, והתשלום מתבצע במועד?', 6, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '7. האם עד ה-15 לכל חודש מכינים דוח למס הכנסה עבור החודש הקודם, והתשלום מתבצע במועד?', 7, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '8. האם עד ה-15 לחודש מכינים דוח לקופות פנסיה, גמל והשתלמות עבור החודש הקודם, והתשלום מועבר במועד?', 8, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '9. האם חשבת השכר מוודאת שהתשלום החודשי לקרן פנסיה ופיצויים תואם את ההתחייבות החודשית?', 9, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '10. האם מורשי החתימה מאשרים בחתימתם את העברת השכר לעובדים לאחר אישור המנהל?', 10, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '11. בתשלום במס"ב - האם דוח הנטו לבנקים מועבר לאישור מורשי החתימה וחתימתם ניתנת על כל עמוד בדוח?', 11, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '12. האם חשבת השכר עורכת בדיקה להתאמת הסכומים שהועברו לסכומים שאושרו על ידי מורשי החתימה?', 12, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '13. האם חשבת השכר מעבירה את דוח הנטו החתום לבנק לביצוע ההעברות?', 13, 
                 NULL, 
                 'radio_with_text', true),
                ('salary_questionnaire_id', '14. האם חשבת השכר עורכת פקודת יומן להעברת השכר במערכת הנהלת החשבונות?', 14, 
                 NULL, 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: security
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('security_questionnaire_id', '1. האם למתנ"ס יש תיק חירום מעודכן לשנה זו?', 1, 
                 'תיק חירום', 
                 'radio_with_text', true),
                ('security_questionnaire_id', '2. האם העתק תיק החירום נמצא בידי גורמים נוספים כנדרש בהנחייה?', 2, 
                 'תיק חירום', 
                 'radio_with_text', true),
                ('security_questionnaire_id', '3. האם קיים דף קשר ונוהלי התקשרות לגופי חירום/מוקדי חירום ונמצא בידי הגורם המוסמך?', 3, 
                 'תיק חירום', 
                 'radio_with_text', true),
                ('security_questionnaire_id', '4. האם במתנ"ס הוכשר נאמן ביטחון, בטיחות וחירום (הג"א)?', 4, 
                 'הכשרות והדרכות', 
                 'radio_with_text', true);


-- שאלות עבור קטגוריה: sgarot
INSERT INTO questions (questionnaire_id, question_text, question_number, section_title, question_type, is_required) 
VALUES 
                ('sgarot_questionnaire_id', '1. האם קיים רישיון לכל התוכניות המצויות במרכז?', 1, 
                 'אבטחת מידע', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '2. האם התוכנות סרוקות בענן?', 2, 
                 'אבטחת מידע', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '3. האם מתבצע גיבוי בהתאם להמלצות הנהלים?', 3, 
                 'אבטחת מידע', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '4. האם מותקן אנטי-וירוס תקף בכל המחשבים?', 4, 
                 'אבטחת מידע', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '5. האם המשתמשים עובדים עם תוכנות החברה בלבד?', 5, 
                 'אבטחת מידע', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '6. האם קיימות חובות משתתפים?', 6, 
                 'אבטחת מידע', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '7. האם קיימות תוכניות עבודה המותאמות לתקציב?', 7, 
                 'שגרות ניהול', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '8. האם למרכז יש חזון ברור?', 8, 
                 'שגרות ניהול', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '9. האם החזון בא לידי ביטוי בתוכניות העבודה?', 9, 
                 'שגרות ניהול', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '10. האם נערכות פגישות קבועות עם ראש הרשות?', 10, 
                 'שגרות ניהול', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '11. האם מתקיימות פגישות שוטפות עם הצוות?', 11, 
                 'שגרות ניהול', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '12. האם נערכות פגישות עם יו"ר ההנהלה?', 12, 
                 'שגרות ניהול', 
                 'radio_with_text', true),
                ('sgarot_questionnaire_id', '13. האם מתקיימת הערכת עובדים באופן סדיר?', 13, 
                 'שגרות ניהול', 
                 'radio_with_text', true);
